services:
  postgres:
    image: postgres:17-alpine
    container_name: Tulisan-notes-postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - isolated

  backend:
    build:
      context: ./backend
    container_name: Tulisan-notes-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - ./backend:/app:Z
      - /app/node_modules

    depends_on:
      - postgres

    networks:
      - public
      - isolated

  frontend:
    build:
      context: ./frontend
    container_name: Tulisan-notes-frontend
    restart: unless-stopped

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app:Z
      - /app/node_modules

    depends_on:
      - backend

    networks:
      - public

volumes:
  postgres_data:

networks:
  public:
    driver: bridge

  isolated:
    driver: bridge
    internal: true
