###
GET http://localhost:8080/

### Register
POST /auth/register
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

name=makruf&email=makruf@mail.com&password=123456

### LOGIN
POST /auth/login
Host: localhost:8080
Content-Type:  application/x-www-form-urlencoded

email=makruf@mail.com&password=123456

### Create Notes

POST /notes
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYWtydWZAbWFpbC5jb20iLCJpYXQiOjE3ODUzMDk2NTMsImV4cCI6MTc4NTM5NjA1M30._pt62X-j0t3Y48VkQK5RkXBN1OJmbbi9MYUssUufwjM

title=Node.js Backend&content=Belajar Express

### Update Note
PUT /notes/1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

title=Belajar Express JS&content=Middleware dan Router

### Delete Notes

DELETE /notes/1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded
